### ISSUE TITLE
Installer can't open optifine's website on linux

### ISSUE THREAD

**Issue by SystemlessDev** [HyperiumClient/Installer#9]
### Java version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

### Stacktrace
`java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.awt.Desktop.checkActionSupport(Desktop.java:221)
	at java.awt.Desktop.browse(Desktop.java:380)
	at cc.hyperium.installer.ui.stages.AddonsSelectionStage$next$1$1$1.invokeSuspend(AddonsSelectionStage.kt:110)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
`

**Comment by ghost** [comment]
Fixed in https://github.com/HyperiumClient/Installer/commit/e420c9791fa7bf3dacc4794d4559b5916e6f6c12
